#!/bin/bash
#-----------------------------------------------------------------------------
# gpg-send-keys-tor
# -----------------
# Upload GPG keys over Tor. The default keyserver is
# hkp://cryptonomicon.mit.edu.
#
# :authors: Isis Agora Lovecruft, 0xa3adb67a2cdb8b35
# :license: GPLv3+
# :version: 0.0.2
#-----------------------------------------------------------------------------

if test $# -lt 1 ; then
    printf "Usage: %s <keyid>\n" "${0%%\/}"
else
    ## This keyserver is hkp://cryptonomicon.mit.edu
    gpg --keyserver hkp://18.9.60.141 \
        --keyserver-options 'verbose no-honor-keyserver-url no-honor-pka-record include-subkeys no-include-attributes http-proxy=socks4a://127.0.0.1:59050' --send-keys $@
fi
