#!/bin/bash
###############################################################################
#
# only
# ----
# only run $@ if it isn't running already.
#
# @author Isis Agora Lovecruft, 0x2cdb8b35
# @date 17 August 2012
# @version 0.0.1
#______________________________________________________________________________
# Changelog:
###############################################################################

if [ -z "`ps -Af | grep -o -w ".*$1" | grep -v grep | grep -v only`" ] ; then
    $@
fi
